function data()
return {
	en = {
		["mod_name"] = "Center Entry Coaches yl (\"Mitteleinstiegswagen\")",
		["mod_desc"] = "To modernize the express train service, the Deutsche Bundesbahn procured new wagons from 1951. They were the first series-production cars with a length of 26.4 m, each with an entry at the end of the car and a double-width entry in the middle. This was arranged slightly asymmetrically. All passenger areas were large rooms with 2+2 seating. From 1956, the 3rd class cars were redesignated as 2nd class. Some cars remained in use until 1994.",

        ["Mitteleinstiegswagen_menu"] = "DB Center Entry Coaches (Group 52)",
        ["rotated"] = " [rotated]",
        ["pulled"] = " [pulled]",
        ["pushed"] = " [pushed]",

        ["AB4yl-51_name"] = "1st/2nd class AB4yl 51",
		["AB4yl-51_desc"] = "1st/2nd class car of Deutsche Bundesbahn group 52. Livery: bottle green",
        ["ABym 411_68_name"] = "1st/2nd class ABym 411 (1968)",
		["ABym 411_68_desc"] = "1st/2nd class car of Deutsche Bundesbahn group 52. Livery: chrome oxide green",
        ["ABym 411_74_name"] = "1st/2nd class ABym 411 (1974)",
		["ABym 411_74_desc"] = "1st/2nd class car of Deutsche Bundesbahn group 52. Livery: turquoise/cream with black frame",
        ["ABym 411_79_name"] = "1st/2nd class ABym 411 (1979)",
		["ABym 411_79_desc"] = "1st/2nd class car of Deutsche Bundesbahn group 52. Livery: turquoise/cream",
        ["B4yl-51_name"] = "2nd class B4yl 51",
		["B4yl-51_desc"] = "2nd class car of Deutsche Bundesbahn group 52. Livery: bottle green",
        ["Bym 421_68_name"] = "2nd class Bym 421 (1968)",
		["Bym 421_68_desc"] = "2nd class car of Deutsche Bundesbahn group 52. Livery: chrome oxide green",
        ["Bym 421_74_name"] = "2nd class Bym 421 (1974)",
		["Bym 421_74_desc"] = "2nd class car of Deutsche Bundesbahn group 52. Livery: turquoise/cream with black frame",
        ["Bym 421_79_name"] = "2nd class Bym 421 (1979)",
		["Bym 421_79_desc"] = "2nd class car der Deutsche Bundesbahn group 52. Livery: turquoise/cream",
        ["B4ymf-51_name"] = "Control car 2nd class B4ymf 51",
		["B4ymf-51_desc"] = "Control car 2nd class of Deutsche Bundesbahn group 52. Livery: bottle green",
        ["Bymf 436_68_name"] = "Control car 2nd class Bymf 436 (1968)",
		["Bymf 436_68_desc"] = "Control car 2nd class of Deutsche Bundesbahn group 52. Livery: chrome oxide green",
        ["Bymf 436_74_name"] = "Control car 2nd class Bymf 436 (1974)",
		["Bymf 436_74_desc"] = "Control car 2nd class of Deutsche Bundesbahn group 52. Livery: turquoise/cream with black frame",
        ["Bymf 436_79_name"] = "Control car 2nd class Bymf 436 (1979)",
		["Bymf 436_79_desc"] = "Control car 2nd class of Deutsche Bundesbahn group 52. Livery: turquoise/cream",
        ["BD4ymf-51_name"] = "Control car 2nd class and luggage compartment B4ymf 51",
		["BD4ymf-51_desc"] = "Control car 2nd class and luggage compartment of Deutsche Bundesbahn group 52. Livery: bottle green",
        ["BDymf 457_68_name"] = "Control car 2nd class and luggage compartment Bymf 436 (1968)",
		["BDymf 457_68_desc"] = "Control car 2nd class and luggage compartment of Deutsche Bundesbahn group 52. Livery: chrome oxide green",
        ["BDymf 457_74_name"] = "Control car 2nd class and luggage compartment Bymf 436 (1974)",
		["BDymf 457_74_desc"] = "Control car 2nd class and luggage compartment of Deutsche Bundesbahn group 52. Livery: turquoise/cream with black frame",
        ["BDymf 457_79_name"] = "Control car 2nd class and luggage compartment Bymf 436 (1979)",
		["BDymf 457_79_desc"] = "Control car 2nd class and luggage compartment of Deutsche Bundesbahn group 52. Livery: turquoise/cream",

        ["C4ymg-51_name"] = "3rd class Cym 51",
        ["C4ymg-51_desc"] = "3rd class car of Deutsche Bundesbahn group 52. Livery: bottle green",
        ["BC4yg-51_name"] = "2nd/3rd class BCym 51",
        ["BC4yg-51_desc"] = "3rd class car of Deutsche Bundesbahn group 52. Livery: bottle green",
        ["C4ymgf-51_name"] = "Control car 3rd class C4ymgf 51",
        ["C4ymgf-51_desc"] = "Control car 3rd class of Deutsche Bundesbahn group 52. Livery: bottle green",
        ["CPwymg-51_name"] = "Control car 3rd class dnd luggage compartment CPw4ymg 51",
        ["CPwymg-51_desc"] = "Control car 3rd class and luggage compartment of Deutsche Bundesbahn group 52. Livery: bottle green",
	},
	de = {
		["mod_name"] = "Mitteleinstiegswagen yl",
		["mod_desc"] = "Zur Modernisierung des Eilzugverkehrs beschaffte die Deutsche Bundesbahn ab 1951 neue Wagen. Es waren die ersten Serienwagen mit einer Länge von 26,4 m mit jeweils einem Einstieg am Wagenende und einem doppeltbreiten Einstieg in der Wagenmitte. Dieser war leicht asymmetrisch angeordnet. Alle Fahrgasträume waren Großräume mit 2+2 Bestuhlung. Ab 1956 wurden die 3. Klasse-Wagen umgezeichnet zur 2. Klasse. Im Einsatz verblieben die Wagen vereinzelt bis 1994.",

        ["Mitteleinstiegswagen_menu"] = "Mitteleinstiegswagen yl (Gruppe 52)",
        ["rotated"] = " [gedreht]",
        ["pulled"] = " [gezogen]",
        ["pushed"] = " [geschoben]",

        ["AB4yl-51_name"] = "1./2. Kl. AB4yl 51",
		["AB4yl-51_desc"] = "1./2. Klasse-Wagen der Deutschen Bundesbahn Gruppe 52. Farbgebung: flaschengrün",
        ["ABym 411_68_name"] = "1./2. Kl. ABym 411 (1968)",
		["ABym 411_68_desc"] = "1./2. Klasse-Wagen der Deutschen Bundesbahn Gruppe 52. Farbgebung: chromoxidgrün",
        ["ABym 411_74_name"] = "1./2. Kl. ABym 411 (1974)",
		["ABym 411_74_desc"] = "1./2. Klasse-Wagen der Deutschen Bundesbahn Gruppe 52. Farbgebung: ozeanblau/elfenbein mit schwarzem Rahmen",
        ["ABym 411_79_name"] = "1./2. Kl. ABym 411 (1979)",
		["ABym_411_79_desc"] = "1./2. Klasse-Wagen der Deutschen Bundesbahn Gruppe 52. Farbgebung: ozeanblau/elfenbein",
        ["B4yl-51_name"] = "2. Kl. B4yl 51",
		["B4yl-51_desc"] = "2. Klasse-Wagen der Deutschen Bundesbahn Gruppe 52. Farbgebung: flaschengrün",
        ["Bym 421_68_name"] = "2. Kl. Bym 421 (1968)",
		["Bym 421_68_desc"] = "2. Klasse-Wagen der Deutschen Bundesbahn Gruppe 52. Farbgebung: chromoxidgrün",
        ["Bym 421_74_name"] = "2. Kl. Bym 421 (1974)",
		["Bym 421_74_desc"] = "2. Klasse-Wagen der Deutschen Bundesbahn Gruppe 52. Farbgebung: ozeanblau/elfenbein mit schwarzem Rahmen",
        ["Bym 421_79_name"] = "2. Kl. Bym 421 (1979)",
		["Bym 421_79_desc"] = "2. Klasse-Wagen der Deutschen Bundesbahn Gruppe 52. Farbgebung: ozeanblau/elfenbein",
        ["B4ymf-51_name"] = "Steuerwagen 2. Kl. B4ymf 51",
		["B4ymf-51_desc"] = "Steuerwagen 2. Klasse der Deutschen Bundesbahn Gruppe 52. Farbgebung: flaschengrün",
        ["Bymf 436_68_name"] = "Steuerwagen 2. Kl. Bymf 436 (1968)",
		["Bymf 436_68_desc"] = "Steuerwagen 2. Klasse der Deutschen Bundesbahn Gruppe 52. Farbgebung: chromoxidgrün",
        ["Bymf 436_74_name"] = "Steuerwagen 2. Kl. Bymf 436 (1974)",
		["Bymf 436_74_desc"] = "Steuerwagen 2. Klasse der Deutschen Bundesbahn Gruppe 52. Farbgebung: ozeanblau/elfenbein mit schwarzem Rahmen",
        ["Bymf 436_79_name"] = "Steuerwagen 2. Kl. Bymf 436 (1979)",
		["Bymf 436_79_desc"] = "Steuerwagen 2. Klasse der Deutschen Bundesbahn Gruppe 52. Farbgebung: ozeanblau/elfenbein",
        ["BD4ymf-51_name"] = "Steuerwg 2. Kl. u. Gepäckabteil B4ymf 51",
		["BD4ymf-51_desc"] = "Steuerwagen 2. Klasse und Gepäckabteil der Deutschen Bundesbahn Gruppe 52. Farbgebung: flaschengrün",
        ["BDymf 457_68_name"] = "Steuerwg 2. Kl. u. Gepäckabteil Bymf 436 (1968)",
		["BDymf 457_68_desc"] = "Steuerwagen 2. Klasse und Gepäckabteil der Deutschen Bundesbahn Gruppe 52. Farbgebung: chromoxidgrün",
        ["BDymf 457_74_name"] = "Steuerwg 2. Kl. u. Gepäckabteil Bymf 436 (1974)",
		["BDymf 457_74_desc"] = "Steuerwagen 2. Klasse und Gepäckabteil der Deutschen Bundesbahn Gruppe 52. Farbgebung: ozeanblau/elfenbein mit schwarzem Rahmen",
        ["BDymf 457_79_name"] = "Steuerwg 2. Kl. u. Gepäckabteil Bymf 436 (1979)",
		["BDymf 457_79_desc"] = "Steuerwagen 2. Klasse und Gepäckabteil der Deutschen Bundesbahn Gruppe 52. Farbgebung: ozeanblau/elfenbein",

        ["C4ymg-51_name"] = "3. Kl. Cym 51",
        ["C4ymg-51_desc"] = "3. Klasse-Wagen der Deutschen Bundesbahn Gruppe 52. Farbgebung: flaschengrün",
        ["BC4yg-51_name"] = "2./3. Kl. BCym 51",
        ["BC4yg-51_desc"] = "2./3. Klasse-Wagen der Deutschen Bundesbahn Gruppe 52. Farbgebung: flaschengrün",
        ["C4ymgf-51_name"] = "Steuerwagen 3. Kl. C4ymgf 51",
        ["C4ymgf-51_desc"] = "Steuerwagen 3. Klasse der Deutschen Bundesbahn Gruppe 52. Farbgebung: flaschengrün",
        ["CPwymg-51_name"] = "Steuerwg 3. Kl. u. Gepäckabteil CPw4ymg 51",
        ["CPwymg-51_desc"] = "Steuerwagen 3. Klasse und Gepäckabteil der Deutschen Bundesbahn Gruppe 52. Farbgebung: flaschengrün",
	},
}
end
